#!/usr/bin/env node
// Vendors the real Inter and JetBrains Mono faces into the tokens package as
// first-party woff2, and generates the @font-face layer that points at them.
//
// Why this exists: naming a font in a stack does not make it available. Strand
// names Inter and JetBrains Mono first, so every consumer had to load them
// somehow, and in practice that meant a runtime request to a font CDN. That is
// a third-party dependency on the critical rendering path of every page, and it
// is the one dependency a design system should not force on its consumers.
//
// Google Fonts serves both families as VARIABLE woff2. One file per subset
// covers the whole weight range the design language uses (Inter 300-600,
// JetBrains Mono 400-600), which is both fewer requests and fewer bytes than
// the static weights it replaces.
//
// Usage:
//   node scripts/vendor-fonts.mjs           refresh binaries + regenerate css
//   node scripts/vendor-fonts.mjs --check    verify checked-in files are current
//
// The generated css and the binaries are both committed, so a consumer install
// never reaches the network and this script only runs when a font is updated.

import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const TOKENS = resolve(HERE, "../packages/tokens");
const FONT_DIR = resolve(TOKENS, "fonts");
const CSS_OUT = resolve(TOKENS, "css/fonts.css");

// The weight ranges the design language actually uses (DL Part IV.5). Asking
// for a narrower range than the font supports produces a smaller file.
const FAMILIES = [
	{ family: "Inter", slug: "inter", query: "Inter:wght@300..600" },
	{
		family: "JetBrains Mono",
		slug: "jetbrains-mono",
		query: "JetBrains+Mono:wght@400..600",
	},
];

// Latin and its extension cover the language the system ships in. Pulling the
// cyrillic and greek subsets would roughly triple the vendored bytes for glyphs
// no current consumer renders; a consumer needing them re-runs this with the
// subset added rather than paying for them by default.
const SUBSETS = ["latin", "latin-ext"];

// Google varies the response by User-Agent: an unrecognised one gets ttf rather
// than woff2. This is a current desktop Chrome.
const UA =
	"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

/**
 * Parses a Google Fonts css2 response into one descriptor per @font-face.
 *
 * Each face is preceded by a comment naming its subset, which is the only place
 * that name appears; a face without one cannot be named and is skipped rather
 * than guessed at.
 *
 * @param {string} css
 * @returns {Array<{family: string, subset: string, weight: string, url: string, unicodeRange: string}>}
 */
export function parseGoogleFontCss(css) {
	const faces = [];
	const blockRe = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/gi;

	for (const match of css.matchAll(blockRe)) {
		const subset = match[1];
		const body = match[2];

		// The url is bare or quoted, and is always followed by format('woff2').
		// Stopping at the closing paren would swallow that; stop at the quote or
		// paren that actually terminates the url instead.
		const url = body.match(/url\(\s*['"]?([^'")\s]+)['"]?\s*\)/)?.[1];
		const family = body.match(/font-family:\s*['"]([^'"]+)['"]/)?.[1];
		const weight = body.match(/font-weight:\s*([^;]+);/)?.[1]?.trim();
		const unicodeRange = body.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim();

		if (!url || !family) continue;
		faces.push({ family, subset, weight: weight ?? "400", url, unicodeRange });
	}

	return faces;
}

/**
 * Generates the @font-face layer for the vendored binaries.
 *
 * Paths are relative to this stylesheet, resolving to a `fonts/` directory that
 * is a sibling of the `css/` directory holding it. That one convention covers
 * both ways consumers take Strand: a bundler rewrites and fingerprints the
 * asset automatically, and a consumer copying files into a web root gets a
 * working path as long as the two directories stay siblings.
 *
 * @param {Array<{family: string, subset: string, weight: string, unicodeRange?: string, file: string}>} faces
 * @returns {string}
 */
export function buildFontFaceCss(faces) {
	const header = `/*! Strand fonts | MIT License | dillingerstaffing.com
 *
 * GENERATED by scripts/vendor-fonts.mjs. Do not edit by hand.
 *
 * The real Inter and JetBrains Mono faces, vendored first-party. Import this
 * alongside tokens.css to serve them from your own origin with no third-party
 * request. Omit it and the stacks in tokens.css fall through to the
 * metric-matched fallbacks in base.css, which is a supported configuration.
 *
 * Paths resolve to a fonts/ directory beside the css/ directory holding this
 * file. Keep them siblings when you copy these into a web root.
 *
 * Both families are variable: one file per subset covers the whole weight
 * range, so there is nothing to add when a new weight starts being used.
 */
`;

	const blocks = faces.map((face) => {
		const lines = [
			"@font-face {",
			`  font-family: '${face.family}';`,
			"  font-style: normal;",
			`  font-weight: ${face.weight};`,
			// Load-bearing, not cosmetic. The default (auto) is treated as block
			// by Chrome, so a face that is slow or missing holds the page blank
			// for up to 3s. swap paints the metric-matched fallback immediately.
			"  font-display: swap;",
			`  src: url('../fonts/${face.file}') format('woff2');`,
		];
		if (face.unicodeRange) lines.push(`  unicode-range: ${face.unicodeRange};`);
		lines.push("}");
		return lines.join("\n");
	});

	return `${header}\n${blocks.join("\n\n")}\n`;
}

async function fetchText(url) {
	const res = await fetch(url, { headers: { "User-Agent": UA } });
	if (!res.ok) throw new Error(`GET ${url} -> ${res.status}`);
	return res.text();
}

async function fetchBinary(url) {
	const res = await fetch(url, { headers: { "User-Agent": UA } });
	if (!res.ok) throw new Error(`GET ${url} -> ${res.status}`);
	return Buffer.from(await res.arrayBuffer());
}

async function main() {
	const check = process.argv.includes("--check");
	await mkdir(FONT_DIR, { recursive: true });

	const generated = [];
	let bytes = 0;

	for (const { family, slug, query } of FAMILIES) {
		const css = await fetchText(
			`https://fonts.googleapis.com/css2?family=${query}&display=swap`,
		);
		const faces = parseGoogleFontCss(css).filter((f) => SUBSETS.includes(f.subset));

		if (faces.length !== SUBSETS.length) {
			throw new Error(
				`${family}: expected ${SUBSETS.length} subsets (${SUBSETS.join(", ")}), got ${faces.length}. ` +
					"The upstream response shape may have changed.",
			);
		}

		for (const face of faces) {
			const file = `${slug}-${face.subset}.woff2`;
			const target = resolve(FONT_DIR, file);
			const buf = await fetchBinary(face.url);

			if (!buf.subarray(0, 4).toString("latin1").startsWith("wOF2")) {
				throw new Error(`${file}: response is not woff2. Check the User-Agent.`);
			}

			const changed =
				!existsSync(target) || !(await readFile(target)).equals(buf);
			if (changed && !check) await writeFile(target, buf);

			bytes += buf.length;
			generated.push({ ...face, file, changed, size: buf.length });
		}
	}

	const css = buildFontFaceCss(generated);
	const cssChanged =
		!existsSync(CSS_OUT) || (await readFile(CSS_OUT, "utf8")) !== css;
	if (!check) await writeFile(CSS_OUT, css);

	const drifted = generated.filter((f) => f.changed);
	for (const f of generated) {
		console.log(
			`  ${f.file.padEnd(34)} ${String(Math.round(f.size / 1024)).padStart(4)} KB  ${f.changed ? "updated" : "current"}`,
		);
	}
	console.log(`\n  total ${Math.round(bytes / 1024)} KB across ${generated.length} files`);
	console.log(`  css   ${CSS_OUT.replace(resolve(HERE, ".."), ".")} ${cssChanged ? "updated" : "current"}`);

	if (check && (drifted.length > 0 || cssChanged)) {
		console.error("\n  FAIL: vendored fonts are stale. Run: node scripts/vendor-fonts.mjs\n");
		process.exit(1);
	}
}

// Only run when invoked directly, so the parser stays importable from tests.
if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
	main().catch((err) => {
		console.error(`\n  ${err.message}\n`);
		process.exit(1);
	});
}
